# reach needs some information about the robot
robot_description_file: 
  package: "ur_custom_description"
  file: "urdf/custom_ur_rotated.urdf.xacro"
robot_description_semantic_file: 
  package: "ur_custom_moveit_config"
  file: "config/custom_ur.srdf"
robot_description_kinematics_file:
  package: "ur_custom_moveit_config"
  file: config/kinematics.yaml
robot_description_joint_limits_file:
  package: "ur_custom_moveit_config"
  file: "config/joint_limits.yaml"
config_file: 
  package: "reach_planner"
  file: "config/reach_config.yaml"
results_dir:
  package: "reach_planner"
  file: "output/results"
config_name: "ur5"

# Specifying the base link name of the robot model is used for creating a virtual joint between world and robot_base_frame
# Don't use this if you already know what you're doing 
robot_base_frame: "robot_mount"
robot_pose: 
  translation: [0.0, 0.0, 0.0]
  rotation_rpy: [0.0, 0.0, 0.0]