# Anchors
planning_group: &planning_group ur_arm
collision_mesh_filename: &collision_mesh_filename package://reach_planner/meshes/cylinder_lower_away.ply

optimization:
  radius: 0.4
  max_steps: 20
  step_improvement_threshold: 0.01

ik_solver:
  name: MoveItIKSolver
  distance_threshold: 0.01
  planning_group: *planning_group
  collision_mesh_filename: *collision_mesh_filename
  touch_links: []

evaluator:
  name: MultiplicativeEvaluator
  plugins:
    - name: ManipulabilityMoveIt
      planning_group: *planning_group
    - name: DistancePenaltyMoveIt
      planning_group: *planning_group
      distance_threshold: 0.05
      exponent: 5
      collision_mesh_filename: *collision_mesh_filename
      touch_links: []

display:
  name: ROSDisplay
  collision_mesh_filename: *collision_mesh_filename
  kinematic_base_frame: world
  marker_scale: 0.05

target_pose_generator:
  name: PointCloudTargetPoseGenerator
  pcd_file: package://reach_planner/output/test_output.pcd

logger:
  name: BoostProgressConsoleLogger
